name: Build and publish

on:
    workflow_dispatch:

env:
    SQLITE_RELEASE_YEAR: "2022"
    SQLITE_VERSION: "3390100"

jobs:
    download-sources:
        name: Download and store sources
        runs-on: ubuntu-20.04
        steps:
            - name: Download sources
              run: |
                  curl -L http://sqlite.org/$SQLITE_RELEASE_YEAR/sqlite-amalgamation-$SQLITE_VERSION.zip --output src.zip
                  unzip src.zip
                  mv sqlite-amalgamation-$SQLITE_VERSION src

            - name: Store sources
              uses: actions/upload-artifact@v2
              with:
                  name: sqlite-sources
                  path: src

    build-windows:
        name: Build for Windows
        runs-on: windows-2019
        needs: download-sources
        steps:
            - uses: actions/download-artifact@v2
              with:
                  name: sqlite-sources
                  path: src

            - name: Compile sources
              shell: bash
              run: |
                  mkdir dist
                  gcc -I. src/shell.c src/sqlite3.c -o dist/sqlite3.exe \
                    -DSQLITE_ENABLE_DBPAGE_VTAB \
                    -DSQLITE_ENABLE_DBSTAT_VTAB \
                    -DSQLITE_ENABLE_EXPLAIN_COMMENTS \
                    -DSQLITE_ENABLE_FTS4 \
                    -DSQLITE_ENABLE_FTS5 \
                    -DSQLITE_ENABLE_GEOPOLY \
                    -DSQLITE_ENABLE_JSON1 \
                    -DSQLITE_ENABLE_MATH_FUNCTIONS \
                    -DSQLITE_ENABLE_OFFSET_SQL_FUNC \
                    -DSQLITE_ENABLE_RTREE \
                    -DSQLITE_ENABLE_STAT4 \
                    -DSQLITE_ENABLE_STMTVTAB \
                    -DSQLITE_ENABLE_UNKNOWN_SQL_FUNCTION \
                    -DSQLITE_LIKE_DOESNT_MATCH_BLOBS \
                    -DSQLITE_THREADSAFE=0 \
                    -DUSE_URI\
                    -DSQLITE_MAX_LENGTH=2147483647\
                    -DSQLITE_MAX_COLUMN=32767\
                    -DSQLITE_MAX_SQL_LENGTH=1073741824\
                    -DSQLITE_MAX_EXPR_DEPTH=0\
                    -DSQLITE_MAX_FUNCTION_ARG=127\
                    -DSQLITE_MAX_PAGE_COUNT=4294967294\
                    -DSQLITE_DEFAULT_PAGE_SIZE=65536\
                    -DSQLITE_DEFAULT_MEMSTATUS=0\
                    -DSQLITE_MAX_MMAP_SIZE=0
                
   
            - name: generate FOO unique variable based on timestamp
              run: echo FOO=foobar--$(date +%s) >> $GITHUB_ENV
                
            - name: Create Release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ env.FOO }}
                release_name: Release ${{ env.FOO }}
