name: Build and publish

on:
    workflow_dispatch:

env:
    SQLITE_RELEASE_YEAR: "2022"
    SQLITE_VERSION: "3390100"

jobs:
    download-sources:
        name: Download and store sources
        runs-on: ubuntu-20.04
        steps:
            - name: Download sources
              run: |
                  curl -L http://sqlite.org/$SQLITE_RELEASE_YEAR/sqlite-amalgamation-$SQLITE_VERSION.zip --output src.zip
                  unzip src.zip
                  mv sqlite-amalgamation-$SQLITE_VERSION src

            - name: Store sources
              uses: actions/upload-artifact@v2
              with:
                  name: sqlite-sources
                  path: src

    build-windows:
        name: Build for Windows
        runs-on: windows-2019
        needs: download-sources
        steps:
            - uses: actions/download-artifact@v2
              with:
                  name: sqlite-sources
                  path: src

            - name: Compile sources
              shell: bash
              run: |
                  mkdir dist
                  gcc -I. src/shell.c src/sqlite3.c -o dist/sqlite3.exe \
                    -DSQLITE_ENABLE_DBPAGE_VTAB \
                    -DSQLITE_ENABLE_DBSTAT_VTAB \
                    -DSQLITE_ENABLE_EXPLAIN_COMMENTS \
                    -DSQLITE_ENABLE_FTS4 \
                    -DSQLITE_ENABLE_FTS5 \
                    -DSQLITE_ENABLE_GEOPOLY \
                    -DSQLITE_ENABLE_JSON1 \
                    -DSQLITE_ENABLE_MATH_FUNCTIONS \
                    -DSQLITE_ENABLE_OFFSET_SQL_FUNC \
                    -DSQLITE_ENABLE_RTREE \
                    -DSQLITE_ENABLE_STAT4 \
                    -DSQLITE_ENABLE_STMTVTAB \
                    -DSQLITE_ENABLE_UNKNOWN_SQL_FUNCTION \
                    -DSQLITE_LIKE_DOESNT_MATCH_BLOBS \
                    -DSQLITE_THREADSAFE=0 \
                    -DUSE_URI

            - name: Upload binaries to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: dist/sqlite3.exe
                  asset_name: sqlite3.exe
                  tag: ${{ env.SQLITE_VERSION }}
